export const Path = {
  // *****************login
  userlogin: "/",
  forget_pass: "/forget_password",
  change_pass: "/change_pass",
  otp_page: "/otp_page",
  // *****************
  // ***************** Superadmin
  superhome: "/superadmin/home",
  CreateAccount: "/superadmin/create",
  Usermanagement: "/superadmin/usermanagement",
  userupdate: "/superadmin/userupdate",
  user: "/superadmin/userupdate/:id",
  Settings: "/superadmin/settings",
  Blocklist: "/superadmin/blocklist",
  // *****************
  // *****************admin
  home: "/admin/home",
  admin_userUpdate: "/admin/userUpdate",
  admin_userUp: "/admin/userUpdate/:userid",
  admin_Report: "/admin/report",
  Admin_CreateAcc: "/admin/Create",
  Admin_Usermanage: "/admin/UserManage",
  Manage_Group: "/admin/Manage_Group",

  Campaign: "/admin/campaingn",
  admin_Traning: "/admin/training",
  admin_instagram: "/admin/Instagram",
  entich_click: "/admin/entich_to_click",
  credential_harvest: "/admin/credential_harvest",
  send_attach: "/admin/send_attachment",
  admin_settings: "/admin/settings",
  admin_blocklist: "/admin/blocklist",
  admin_entich_table: "/admin/entich_table",
  admin_entich_table_id: "/admin/entich_table/:clickid",
  admin_harvest_table: "/admin/harvest_table",
  admin_harvest_table_id: "/admin/harvest_table/:clickid",
  admin_send_table: "/admin/send_attach_table",
  admin_send_table_id: "/admin/send_attach_table/:clickid",
  admin_form_popup: "/admin/form_popup",
  admin_Profile: "/admin/Profile",
  all_campaigns: "/admin/all_campaigns",
  active_campaigns: "/admin/active_campaigns",
  completed_campaigns: "/admin/completed_campaigns",
  training_campaigns: "/admin/training_campaigns",
  awarness_dashboard: "/admin/awarness_dashboard",
  report_group: "/admin/Group_wise",
  report_desig: "/admin/Designation_wise",
  report_dept: "/admin/Department_wise",
  assign_form: "/admin/assign_form",
  assign_traing: "/admin/assign_training",
  my_template: "/admin/my_template",
  aware_template: "/admin/aware_template",
  system_template: "/admin/system_template",

  // *****************
  // *****************user
  Usertraining: "/_user/training",
  user_instagram: "/_user/Instagram",
  user_settings: "/_user/settings",
  user_dash: "/_userdash",
  // Admin_User_Profile: "/userProfile",
  // ----------------------
  user_profile: "/_user/Profile",
};
